// Directors data from CSV
export const directorsData = [
  {
    firstName: "Dat",
    lastName: "Le",
    clinic: "Accounting",
    role: "Clinic Director",
    email: "dat.le@mottafinancial.com",
  },
  {
    firstName: "Grace",
    lastName: "Cha",
    clinic: "Accounting",
    role: "Clinic Director",
    email: "HyeeEun.Cha@su.suffolk.edu",
  },
  {
    firstName: "Mark",
    lastName: "Dwyer",
    clinic: "Accounting",
    role: "Clinic Director",
    email: "Mark.Dwyer@suffolk.edu",
  },
  {
    firstName: "Ken",
    lastName: "Mooney",
    clinic: "Resource Acquisition",
    role: "Clinic Director",
    email: "kmooney@suffolk.edu",
  },
  {
    firstName: "Dmitri",
    lastName: "Tcherevik",
    clinic: "Artificial Intelligence",
    role: "SEED Support",
    email: "Dmitri.Tcherevik@suffolk.edu",
  },
  { firstName: "Chaim", lastName: "Letwin", clinic: "Management", role: "SEED Support", email: "cletwin@suffolk.edu" },
  {
    firstName: "Nick",
    lastName: "Vadala",
    clinic: "Consulting",
    role: "Clinic Director",
    email: "nvadala@suffolk.edu",
  },
  {
    firstName: "Beth",
    lastName: "DiRusso",
    clinic: "Legal",
    role: "Clinic Director",
    email: "Elizabeth.DiRusso@suffolk.edu",
  },
  {
    firstName: "Chris",
    lastName: "Hill",
    clinic: "Marketing",
    role: "Clinic Director",
    email: "Christopher.Hill@suffolk.edu",
  },
  { firstName: "Boris", lastName: "Lazic", clinic: "Management", role: "SEED Support", email: "blazic@suffolk.edu" },
  {
    firstName: "Darrell",
    lastName: "Mottley",
    clinic: "Legal",
    role: "SEED Support",
    email: "Darrell.Mottley@suffolk.edu",
  },
]

// Students data from CSV
export const studentsData = [
  {
    firstName: "Mahekdeep Kaur Charanjit Singh",
    lastName: "Abrol",
    email: "Mahek.Abrol@su.suffolk.edu",
    clinic: "Marketing",
    clientTeam: "Marabou",
    isTeamLeader: false,
    academicLevel: "Undergraduate",
    universityId: "UID007758228",
  },
  {
    firstName: "Stuti",
    lastName: "Adhikari",
    email: "Stuti.Adhikari@su.suffolk.edu",
    clinic: "Accounting",
    clientTeam: "Crown Legends",
    isTeamLeader: false,
    academicLevel: "Undergraduate",
    universityId: "UID007701764",
  },
  {
    firstName: "Aiman",
    lastName: "Albatati",
    email: "Aiman.Albatati@su.suffolk.edu",
    clinic: "Legal",
    clientTeam: "CRE Boston",
    isTeamLeader: false,
    academicLevel: "Graduate",
    universityId: "UID007769193",
  },
  {
    firstName: "Duaa",
    lastName: "Albattah",
    email: "Duaa.Albattah@su.suffolk.edu",
    clinic: "Accounting",
    clientTeam: "Prime Pay",
    isTeamLeader: false,
    academicLevel: "Undergraduate",
    universityId: "UID007686649",
  },
  {
    firstName: "Saud",
    lastName: "Alsulami",
    email: "Saud.Alsulami@su.suffolk.edu",
    clinic: "Legal",
    clientTeam: "CRE Boston",
    isTeamLeader: false,
    academicLevel: "Graduate",
    universityId: "UID007638655",
  },
  {
    firstName: "Emnet",
    lastName: "Bekele",
    email: "Emnet.Bekele@su.suffolk.edu",
    clinic: "Marketing",
    clientTeam: "Marabou",
    isTeamLeader: false,
    academicLevel: "Undergraduate",
    universityId: "UID007588990",
  },
  {
    firstName: "Christian",
    lastName: "Biundo",
    email: "Christian.Biundo@su.suffolk.edu",
    clinic: "Consulting",
    clientTeam: "Divert",
    isTeamLeader: true,
    academicLevel: "Undergraduate",
    universityId: "UID007565312",
  },
  {
    firstName: "Joshua",
    lastName: "Carter",
    email: "Joshua.Carter@su.suffolk.edu",
    clinic: "Marketing",
    clientTeam: "Prime Pay",
    isTeamLeader: false,
    academicLevel: "Undergraduate",
    universityId: "UID007726710",
  },
  {
    firstName: "Anupama",
    lastName: "Chandrashekar",
    email: "Anupama.Chandrashekar@su.suffolk.edu",
    clinic: "Marketing",
    clientTeam: "Everon",
    isTeamLeader: false,
    academicLevel: "Graduate",
    universityId: "UID007613399",
  },
  {
    firstName: "Sravanthi",
    lastName: "Chilla",
    email: "Sravanthi.Chilla@su.suffolk.edu",
    clinic: "Marketing",
    clientTeam: "Marabou",
    isTeamLeader: true,
    academicLevel: "Graduate",
    universityId: "UID007769218",
  },
  {
    firstName: "Ethan",
    lastName: "Davis",
    email: "Ethan.Davis2@su.suffolk.edu",
    clinic: "Consulting",
    clientTeam: "Divert",
    isTeamLeader: false,
    academicLevel: "Undergraduate",
    universityId: "UID007747566",
  },
  {
    firstName: "Emma",
    lastName: "Duffy",
    email: "Emma.Duffy@su.suffolk.edu",
    clinic: "Marketing",
    clientTeam: "Rewind Pain",
    isTeamLeader: true,
    academicLevel: "Undergraduate",
    universityId: "UID007706936",
  },
  {
    firstName: "Adler",
    lastName: "Fonseca",
    email: "Adler.Fonseca@su.suffolk.edu",
    clinic: "Accounting",
    clientTeam: "Crown Legends",
    isTeamLeader: false,
    academicLevel: "Graduate",
    universityId: "UID007757108",
  },
  {
    firstName: "Shukurat",
    lastName: "Giwa",
    email: "Shukurat.Giwa@su.suffolk.edu",
    clinic: "Marketing",
    clientTeam: "Marabou",
    isTeamLeader: false,
    academicLevel: "Graduate",
    universityId: "UID007762254",
  },
  {
    firstName: "Sunil",
    lastName: "Gurung",
    email: "Sunil.Gurung@su.suffolk.edu",
    clinic: "Accounting",
    clientTeam: "Rewind Pain",
    isTeamLeader: true,
    academicLevel: "Undergraduate",
    universityId: "UID007589186",
  },
  {
    firstName: "Jennifer",
    lastName: "Hernandez",
    email: "Jennifer.Hernandez@su.suffolk.edu",
    clinic: "Marketing",
    clientTeam: "Rewind Pain",
    isTeamLeader: false,
    academicLevel: "Undergraduate",
    universityId: "UID007698692",
  },
  {
    firstName: "David",
    lastName: "Khut",
    email: "David.Khut@su.suffolk.edu",
    clinic: "Marketing",
    clientTeam: "Rewind Pain",
    isTeamLeader: false,
    academicLevel: "Undergraduate",
    universityId: "UID007711914",
  },
  {
    firstName: "Alexis",
    lastName: "LaBella",
    email: "Alexis.LaBella@su.suffolk.edu",
    clinic: "Accounting",
    clientTeam: "Divert",
    isTeamLeader: false,
    academicLevel: "Undergraduate",
    universityId: "UID007747780",
  },
  {
    firstName: "Lam",
    lastName: "Le",
    email: "Lam.Le@su.suffolk.edu",
    clinic: "Accounting",
    clientTeam: "Prime Pay",
    isTeamLeader: true,
    academicLevel: "Undergraduate",
    universityId: "UID007588958",
  },
  {
    firstName: "Emily",
    lastName: "Leung",
    email: "Emily.Leung@su.suffolk.edu",
    clinic: "Accounting",
    clientTeam: "Prime Pay",
    isTeamLeader: false,
    academicLevel: "Undergraduate",
    universityId: "UID007703696",
  },
  {
    firstName: "Evan",
    lastName: "Marchi",
    email: "Evan.Marchi@su.suffolk.edu",
    clinic: "Consulting",
    clientTeam: "Everon",
    isTeamLeader: true,
    academicLevel: "Undergraduate",
    universityId: "UID007711330",
  },
  {
    firstName: "Collin",
    lastName: "Merwin",
    email: "Collin.Merwin@su.suffolk.edu",
    clinic: "Accounting",
    clientTeam: "Everon",
    isTeamLeader: false,
    academicLevel: "Undergraduate",
    universityId: "UID007729688",
  },
  {
    firstName: "Seyedparsa",
    lastName: "Neshatavar",
    email: "Seyedparsa.Neshatavar@su.suffolk.edu",
    clinic: "Accounting",
    clientTeam: "Crown Legends",
    isTeamLeader: true,
    academicLevel: "Graduate",
    universityId: "UID007636574",
  },
  {
    firstName: "Chika",
    lastName: "Odinkemere",
    email: "Chizoba.Odinkemere@su.suffolk.edu",
    clinic: "Accounting",
    clientTeam: "Divert",
    isTeamLeader: true,
    academicLevel: "Undergraduate",
    universityId: "UID007729694",
  },
  {
    firstName: "Elma",
    lastName: "Okic",
    email: "Elma.Okic@su.suffolk.edu",
    clinic: "Consulting",
    clientTeam: "Divert",
    isTeamLeader: false,
    academicLevel: "Undergraduate",
    universityId: "UID007755116",
  },
  {
    firstName: "Maelys",
    lastName: "Paschal",
    email: "Maelys.Paschal@su.suffolk.edu",
    clinic: "Accounting",
    clientTeam: "Everon",
    isTeamLeader: true,
    academicLevel: "Graduate",
    universityId: "UID007769175",
  },
  {
    firstName: "Dominick",
    lastName: "Pham",
    email: "Dominick.Pham@su.suffolk.edu",
    clinic: "Consulting",
    clientTeam: "TBA",
    isTeamLeader: true,
    academicLevel: "Undergraduate",
    universityId: "UID007711388",
  },
  {
    firstName: "Yasin",
    lastName: "Popal",
    email: "Yasin.Popal@su.suffolk.edu",
    clinic: "Consulting",
    clientTeam: "Everon",
    isTeamLeader: false,
    academicLevel: "Undergraduate",
    universityId: "UID007731574",
  },
  {
    firstName: "Oshadi",
    lastName: "Ranasinghe",
    email: "Oshadi.Ranasinghe@su.suffolk.edu",
    clinic: "Accounting",
    clientTeam: "TBA",
    isTeamLeader: false,
    academicLevel: "Graduate",
    universityId: "UID007764696",
  },
  {
    firstName: "Amisha",
    lastName: "Sapkota",
    email: "Amisha.Sapkota@su.suffolk.edu",
    clinic: "Consulting",
    clientTeam: "Divert",
    isTeamLeader: false,
    academicLevel: "Graduate",
    universityId: "UID007757356",
  },
  {
    firstName: "Sanjana",
    lastName: "Sathish",
    email: "Sanjana.Sathish@su.suffolk.edu",
    clinic: "Marketing",
    clientTeam: "Everon",
    isTeamLeader: true,
    academicLevel: "Graduate",
    universityId: "UID007769200",
  },
  {
    firstName: "Lisa",
    lastName: "Shatri",
    email: "Lisa.Shatri@su.suffolk.edu",
    clinic: "Accounting",
    clientTeam: "Divert",
    isTeamLeader: false,
    academicLevel: "Undergraduate",
    universityId: "UID007703658",
  },
  {
    firstName: "Jenish",
    lastName: "Shrestha",
    email: "Jenish.Shrestha@su.suffolk.edu",
    clinic: "Consulting",
    clientTeam: "Divert",
    isTeamLeader: false,
    academicLevel: "Graduate",
    universityId: "UID007754606",
  },
  {
    firstName: "Rima",
    lastName: "Shrestha",
    email: "Rima.Shrestha@su.suffolk.edu",
    clinic: "Consulting",
    clientTeam: "Divert",
    isTeamLeader: false,
    academicLevel: "Graduate",
    universityId: "UID007763988",
  },
  {
    firstName: "Aadesh",
    lastName: "Subedi",
    email: "Aadesh.Subedi@su.suffolk.edu",
    clinic: "Accounting",
    clientTeam: "Rewind Pain",
    isTeamLeader: false,
    academicLevel: "Graduate",
    universityId: "UID007768529",
  },
  {
    firstName: "Ashmita",
    lastName: "Subedi",
    email: "Ashmita.Subedi@su.suffolk.edu",
    clinic: "Accounting",
    clientTeam: "Divert",
    isTeamLeader: false,
    academicLevel: "Graduate",
    universityId: "UID007768477",
  },
  {
    firstName: "Madesh",
    lastName: "Sundararajan",
    email: "Madesh.Sundararajan@su.suffolk.edu",
    clinic: "Consulting",
    clientTeam: "TBA",
    isTeamLeader: false,
    academicLevel: "Graduate",
    universityId: "UID007757116",
  },
  {
    firstName: "Sariza",
    lastName: "Thapa",
    email: "Sariza.Thapa@su.suffolk.edu",
    clinic: "Marketing",
    clientTeam: "Everon",
    isTeamLeader: false,
    academicLevel: "Graduate",
    universityId: "UID007757350",
  },
  {
    firstName: "Julie",
    lastName: "Tran",
    email: "Julie.Tran2@su.suffolk.edu",
    clinic: "Accounting",
    clientTeam: "Crown Legends",
    isTeamLeader: false,
    academicLevel: "Undergraduate",
    universityId: "UID007721858",
  },
  {
    firstName: "Nancy",
    lastName: "Tran",
    email: "Nancy.Tran@su.suffolk.edu",
    clinic: "Marketing",
    clientTeam: "Prime Pay",
    isTeamLeader: true,
    academicLevel: "Undergraduate",
    universityId: "UID007744948",
  },
  {
    firstName: "Ngan",
    lastName: "Truong",
    email: "Ngan.Truong@su.suffolk.edu",
    clinic: "Marketing",
    clientTeam: "Prime Pay",
    isTeamLeader: false,
    academicLevel: "Graduate",
    universityId: "UID007757058",
  },
  {
    firstName: "Ashley",
    lastName: "Vo",
    email: "Ashley.Vo2@su.suffolk.edu",
    clinic: "Marketing",
    clientTeam: "Rewind Pain",
    isTeamLeader: false,
    academicLevel: "Undergraduate",
    universityId: "UID007729688",
  },
  {
    firstName: "Joselina",
    lastName: "Vargas",
    email: "Joselina.Vargas@su.suffolk.edu",
    clinic: "Marketing",
    clientTeam: "Marabou",
    isTeamLeader: false,
    academicLevel: "Undergraduate",
    universityId: "UID007752966",
  },
]

// Clients data from CSV
export const clientsData = [
  {
    name: "Everon",
    status: "Active",
    semester: "Spring 2025",
    contactName: "",
    contactEmail: "",
    projectType: "Accounting/Marketing/Consulting",
    clinics: ["Accounting", "Marketing", "Consulting"],
  },
  {
    name: "Divert",
    status: "Active",
    semester: "Spring 2025",
    contactName: "",
    contactEmail: "",
    projectType: "Accounting/Consulting",
    clinics: ["Accounting", "Consulting"],
  },
  {
    name: "Prime Pay",
    status: "Active",
    semester: "Spring 2025",
    contactName: "",
    contactEmail: "",
    projectType: "Accounting/Marketing",
    clinics: ["Accounting", "Marketing"],
  },
  {
    name: "Rewind Pain",
    status: "Active",
    semester: "Spring 2025",
    contactName: "",
    contactEmail: "",
    projectType: "Accounting/Marketing",
    clinics: ["Accounting", "Marketing"],
  },
  {
    name: "Crown Legends",
    status: "Active",
    semester: "Spring 2025",
    contactName: "",
    contactEmail: "",
    projectType: "Accounting",
    clinics: ["Accounting"],
  },
  {
    name: "Marabou",
    status: "Active",
    semester: "Spring 2025",
    contactName: "",
    contactEmail: "",
    projectType: "Marketing",
    clinics: ["Marketing"],
  },
  {
    name: "CRE Boston",
    status: "Active",
    semester: "Spring 2025",
    contactName: "",
    contactEmail: "",
    projectType: "Legal",
    clinics: ["Legal"],
  },
  {
    name: "TBA",
    status: "Pending",
    semester: "Spring 2025",
    contactName: "",
    contactEmail: "",
    projectType: "Consulting",
    clinics: ["Consulting"],
  },
]
